apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ivolve
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIzNA== # Base64 encoded value for "password"
  MYSQL_PASSWORD: MTIzNA==    # Base64 encoded value for "user_pass"

