apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command:
        - "sh"
        - "-c"
        - "chmod -R 777 /var/cache/nginx"
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
